### ISSUE TITLE
Linking to "how to install" guides if they are provided in the documentation, instead of creating our own version.

### ISSUE THREAD

**Issue by alichtman** [moghya/install-it#5]
For example, https://github.com/atom/atom/#installing covers installing Atom much better than any of us could, and it'll stay updated as the install process changes. 

Opinions on starting a document with links to good install guides provided by the devs themselves?

I think we should have one `native_documentation.md` file with entries like:

```markdown
[Atom](https://github.com/atom/atom/#installing)
...
```

and we will maintain an index of what applications/tools we cover in our README, instead of each having its own file, necessarily.

**Comment by alichtman** [comment]
Instead of creating an extra file for this, I just threw it at the bottom of the README. I think this is a decently elegant solution, and will save a lot of needless effort. Guides should only be written for things that don't already have solid documentation.

**Comment by alichtman** [comment]
Once PR #7 is merged, this can be closed as it will be documented in the Contributing guide.

**Comment by moghya** [comment]
Closing as #7 is merged.
